### ISSUE TITLE
BlueMlik Logo

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JasperFx/bluemilk#67]
An initial spike of a **BlueMilk** logo. I tried to get as close to the **Star Wars** blue milk color as I could.

![bluemilk](https://user-images.githubusercontent.com/228256/36646312-0ef20548-1a44-11e8-9688-dd6e71ba4a87.png)

credit for the cup goes to https://thenounproject.com/souvik.maity.52 from the noun project.

---

![bluemilk_full](https://user-images.githubusercontent.com/228256/36646365-a9cc722e-1a44-11e8-8673-21d998f2b406.png)
![bluemilk_circle](https://user-images.githubusercontent.com/228256/36646367-abfd7890-1a44-11e8-8db4-79e5156057c7.png)
![bluemilk_b](https://user-images.githubusercontent.com/228256/36646369-add05c46-1a44-11e8-8064-7f939c6d1305.png)

**Comment by jeremydmiller** [comment]
*I* like it. The only remaining question though is whether we go with this name or change it. The reactions have been pretty mixed.

**Comment by JosephWoodward** [comment]
I'm in the change it camp. BlueMilk sounds rather revolting lol.

Considering its close ties to StructureMap and StructureMap's APIs - do you think it would be worth leaving some reference to StructureMap (somehow) in the name?

**Comment by CodingGorilla** [comment]
It seems an odd name to me, but I have no really strong feelings about it either.  If you abbreviate it like you would StructureMap, you get BM, which can have some other connotations. 😆

**Comment by jeremydmiller** [comment]
@CodingGorilla As opposed to StructureMap that gets abbreviated "SM" in the era of Fifty Shades?

**Comment by jeremydmiller** [comment]
Well, and the part where StructureMap was **supposed** to be an ORM and what you see now is just the descendent of the configuration model for the failed ORM framework

**Comment by JosephWoodward** [comment]
StructureMap was supposed to be an ORM!? How did that happen?

**Comment by khalidabuhakmeh** [comment]
Had this idea bouncing around in my head and wanted to do it just to keep it from making me go nuts. No hurt feelings if you pass, promise :)

Next step is:

![huge_avatar](https://user-images.githubusercontent.com/228256/36867449-22de5008-1d63-11e8-93a0-17a34e6dd338.png)

**Comment by cocowalla** [comment]
As much as I dislike the name Blue Milk, these logos do look really good 🥇

**Comment by JosephWoodward** [comment]
Ooh, me thinks @jeremydmiller has a new name for BlueMilk! https://github.com/JasperFx/lamar

**Comment by jeremydmiller** [comment]
It probably won't make for as cool a logo as @khalidabuhakmeh, but I'm renaming this puppy to "Lamar" sometime this week. Purposely using a boring name for some historical reasons

**Comment by CodingGorilla** [comment]
![https://spiritofthething.files.wordpress.com/2013/04/revenge-of-the-nerds-lamar.jpg](url)

Lamar?
