### ISSUE TITLE
TransientLambdaResolver can generate invalid code

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/bluemilk#68]
A `TransientLambdaResolver` will generate code that uses a `Func<IContainer, T>` to generate an instance, but is passed a `Scope` instance as an argument to the `TransientResolver.Build()` method.  This results in an attempt to cast the `Scope` to `IContainer` which in turn generates an `InvalidCastException`.

**Comment by jeremydmiller** [comment]
Closed by #69
