### ISSUE TITLE
Eliminate dependencies to avoid transitive hell issues

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/bluemilk#73]
Think these things are giving me issues w/ transitive dependencies downstream in Jasper and I had meant to do this sooner or later anyway, so....

- [x] Baseline -- steal the extension methods we're using and make them internal inside of BlueMilk
- [x] ImTools -- just take ImHashMap and call it a day
- [x] FastExpressionCompiler -- not 100% sure this is really helping. Might eliminate.

**Comment by CodingGorilla** [comment]
> Baseline -- steal the extension methods we're using and make them internal inside of ~~Baseline~~ BlueMilk

Right?

**Comment by jeremydmiller** [comment]
Pfft, yes.
